### ISSUE TITLE
Add project documentation to repo

### ISSUE THREAD

**Issue by oubiwann** [clojusc/friend-oauth2#39]
Tasks:
 * [x] Update `project.clj` with docs profile and codx plugin - #40
 * [x] Generate and publish API Reference docs - #41
 * [x] Convert wiki page to Codox "Topics" - #42
 * [x] Migrate bits of README into Codox "Topics" - #55

Part of release #51
