### ISSUE TITLE
Integrate examples into this repo

### ISSUE THREAD

**Issue by oubiwann** [clojusc/friend-oauth2#43]
Tasks:
 * [x] Identify means of keeping source code and example code separate - #44
 * [x] Update `project.clj` with the selected approach - #45
 * [x] Copy source code from example repo - #46
 * [x] Put deprecation notice on example repo `README` - #47
 * [x] Add documentation for each example - #48 (depends upon #39)

Part of release #51

**Comment by oubiwann** [comment]
Done.
