### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by oubiwann** [clojusc/friend-oauth2#64]
The overall goal of these release is to improve the user experience of friend-oauth2. In particular, focus will be put upon the examples, providing a recommendation for fully backwards-compatible boilerplate reduction.

Features:
 * [ ] Recommend a best practice for configuring workflows - #49
 * [ ] Provide helper namespaces for contributed workflows - #50
 * [ ] Improve Code Documentation - #60
